name: Deployment to Andasy With nested project
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: quarksgroup/andasy-action@main
        env:
          # Set access token
          ANDASY_ACCESS_TOKEN: ${{ secrets.apptoken }}
        with:
          # Specifying custom deployment directory, relative to the root of the repository
          project_path: server2